# The Docker image that will be used to build your app
stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: "postgresql://postgres@db:5432/mydatabase"

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - main
